name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/must-bioinfo/fastCNV.git
          git fetch upstream
          git checkout master || git checkout main
          git merge upstream/master --ff-only || git merge upstream/main --ff-only
          git push origin HEAD
